name: Main - Merge FIDO Metadata

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *' 
    
permissions:
  contents: write

jobs:
  merge-fido-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Install JWTDetails Module
        shell: pwsh
        run: Install-Module -Name JWTDetails -Force -Scope CurrentUser

      - name: Run Merge-FidoMetaData.ps1
        shell: pwsh
        run: |
          Import-Module -Name JWTDetails
          ./Scripts/Merge-GHFIDOMetaData.ps1

      - name: Configure Git
        run: |
          git config --global user.name 'DevClate'
          git config --global user.email 'clate@clatent.com'

      - name: Commit changes
        run: |
          git add Assets/FidoKeys.json FAmerge_log.txt
          git commit -m "Update FidoKeys.json and FAmerge_log.txt" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
